### ISSUE TITLE
No hay avances del proyecto

### ISSUE THREAD

**Issue by norman-ipn** [Jair-lechuga/proyecto-final#3]
¿Todavía quieren que evalúe el proyecto?
@bryan-lm 
@IandelaTorre 
@Jair-lechuga

**Comment by bryan-lm** [comment]
si @norman-ipn

**Comment by IandelaTorre** [comment]
Si profesor el día de hoy subiremos el progreso.

**Comment by MiguelG52** [comment]
Cámara niños, ni han subido nada XD
F
