### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by Jair-lechuga** [Jair-lechuga/proyecto-final#4]
@bryan-lm  y @IandelaTorre  revisen el readme, modifique algunas cosillas, que más falta agregarle a esa parte y a la wiki??

**Comment by IandelaTorre** [comment]
En esa parte solo era una descripción yo creo que ya está bien y en la wiki no sé que más le tengamos que agregar.

**Comment by bryan-lm** [comment]
@Jair-lechuga si solo es una descripción
